import java.util.HashMap;

import DataStructures.Pair;

public class definitions {
    public static Pair<String, Integer>[][] tablaAccion() {
        Pair<String, Integer>[][] tablaAccion = new Pair[105][29];
        tablaAccion[0][0] = new Pair<>("S", 13);
        tablaAccion[0][1] = new Pair<>("S", 9);
        tablaAccion[0][9] = new Pair<>("S", 10);
        tablaAccion[0][10] = new Pair<>("S", 11);
        tablaAccion[0][11] = new Pair<>("S", 12);
        tablaAccion[0][13] = new Pair<>("S", 4);
        tablaAccion[0][14] = new Pair<>("S", 5);
        tablaAccion[0][15] = new Pair<>("S", 7);
        tablaAccion[0][28] = new Pair<>("R", 3);
        tablaAccion[1][28] = new Pair<>("ACC", null);
        tablaAccion[2][0] = new Pair<>("S", 13);
        tablaAccion[2][1] = new Pair<>("S", 9);
        tablaAccion[2][9] = new Pair<>("S", 10);
        tablaAccion[2][10] = new Pair<>("S", 11);
        tablaAccion[2][11] = new Pair<>("S", 12);
        tablaAccion[2][13] = new Pair<>("S", 4);
        tablaAccion[2][14] = new Pair<>("S", 5);
        tablaAccion[2][15] = new Pair<>("S", 7);
        tablaAccion[2][28] = new Pair<>("R", 3);
        tablaAccion[3][0] = new Pair<>("S", 13);
        tablaAccion[3][1] = new Pair<>("S", 9);
        tablaAccion[3][9] = new Pair<>("S", 10);
        tablaAccion[3][10] = new Pair<>("S", 11);
        tablaAccion[3][11] = new Pair<>("S", 12);
        tablaAccion[3][13] = new Pair<>("S", 4);
        tablaAccion[3][14] = new Pair<>("S", 5);
        tablaAccion[3][15] = new Pair<>("S", 7);
        tablaAccion[3][28] = new Pair<>("R", 3);
        tablaAccion[4][2] = new Pair<>("S", 16);
        tablaAccion[5][17] = new Pair<>("S", 18);
        tablaAccion[5][18] = new Pair<>("S", 19);
        tablaAccion[5][19] = new Pair<>("S", 20);
        tablaAccion[6][0] = new Pair<>("R", 24);
        tablaAccion[6][1] = new Pair<>("R", 24);
        tablaAccion[6][3] = new Pair<>("R", 24);
        tablaAccion[6][5] = new Pair<>("R", 24);
        tablaAccion[6][9] = new Pair<>("R", 24);
        tablaAccion[6][10] = new Pair<>("R", 24);
        tablaAccion[6][11] = new Pair<>("R", 24);
        tablaAccion[6][13] = new Pair<>("R", 24);
        tablaAccion[6][14] = new Pair<>("R", 24);
        tablaAccion[6][15] = new Pair<>("R", 24);
        tablaAccion[6][28] = new Pair<>("R", 24);
        tablaAccion[7][4] = new Pair<>("S", 21);
        tablaAccion[8][2] = new Pair<>("S", 23);
        tablaAccion[9][2] = new Pair<>("S", 25);
        tablaAccion[9][7] = new Pair<>("S", 24);
        tablaAccion[9][12] = new Pair<>("S", 26);
        tablaAccion[10][2] = new Pair<>("S", 27);
        tablaAccion[11][2] = new Pair<>("S", 28);
        tablaAccion[12][1] = new Pair<>("S", 35);
        tablaAccion[12][2] = new Pair<>("S", 36);
        tablaAccion[12][8] = new Pair<>("R", 49);
        tablaAccion[12][26] = new Pair<>("S", 37);
        tablaAccion[12][27] = new Pair<>("S", 38);
        tablaAccion[13][1] = new Pair<>("R", 9);
        tablaAccion[13][17] = new Pair<>("S", 18);
        tablaAccion[13][18] = new Pair<>("S", 19);
        tablaAccion[13][19] = new Pair<>("S", 20);
        tablaAccion[14][28] = new Pair<>("R", 1);
        tablaAccion[15][28] = new Pair<>("R", 2);
        tablaAccion[16][1] = new Pair<>("S", 35);
        tablaAccion[16][2] = new Pair<>("S", 36);
        tablaAccion[16][26] = new Pair<>("S", 37);
        tablaAccion[16][27] = new Pair<>("S", 38);
        tablaAccion[17][1] = new Pair<>("S", 42);
        tablaAccion[18][1] = new Pair<>("R", 26);
        tablaAccion[19][1] = new Pair<>("R", 27);
        tablaAccion[20][1] = new Pair<>("R", 28);
        tablaAccion[21][1] = new Pair<>("S", 9);
        tablaAccion[21][9] = new Pair<>("S", 10);
        tablaAccion[21][10] = new Pair<>("S", 11);
        tablaAccion[21][11] = new Pair<>("S", 12);
        tablaAccion[21][13] = new Pair<>("S", 4);
        tablaAccion[21][14] = new Pair<>("S", 5);
        tablaAccion[21][15] = new Pair<>("S", 7);
        tablaAccion[22][4] = new Pair<>("S", 45);
        tablaAccion[23][3] = new Pair<>("R", 11);
        tablaAccion[23][17] = new Pair<>("S", 18);
        tablaAccion[23][18] = new Pair<>("S", 19);
        tablaAccion[23][19] = new Pair<>("S", 20);
        tablaAccion[24][1] = new Pair<>("S", 35);
        tablaAccion[24][2] = new Pair<>("S", 36);
        tablaAccion[24][26] = new Pair<>("S", 37);
        tablaAccion[24][27] = new Pair<>("S", 38);
        tablaAccion[25][1] = new Pair<>("S", 35);
        tablaAccion[25][2] = new Pair<>("S", 36);
        tablaAccion[25][3] = new Pair<>("R", 45);
        tablaAccion[25][8] = new Pair<>("R", 45);
        tablaAccion[25][26] = new Pair<>("S", 37);
        tablaAccion[25][27] = new Pair<>("S", 38);
        tablaAccion[26][1] = new Pair<>("S", 35);
        tablaAccion[26][2] = new Pair<>("S", 36);
        tablaAccion[26][3] = new Pair<>("R", 45);
        tablaAccion[26][8] = new Pair<>("R", 45);
        tablaAccion[26][26] = new Pair<>("S", 37);
        tablaAccion[26][27] = new Pair<>("S", 38);
        tablaAccion[27][1] = new Pair<>("S", 35);
        tablaAccion[27][2] = new Pair<>("S", 36);
        tablaAccion[27][26] = new Pair<>("S", 37);
        tablaAccion[27][27] = new Pair<>("S", 38);
        tablaAccion[28][1] = new Pair<>("S", 53);
        tablaAccion[29][8] = new Pair<>("S", 54);
        tablaAccion[30][8] = new Pair<>("R", 48);
        tablaAccion[30][20] = new Pair<>("S", 55);
        tablaAccion[31][3] = new Pair<>("R", 30);
        tablaAccion[31][6] = new Pair<>("R", 30);
        tablaAccion[31][8] = new Pair<>("R", 30);
        tablaAccion[31][20] = new Pair<>("R", 30);
        tablaAccion[31][21] = new Pair<>("S", 56);
        tablaAccion[32][3] = new Pair<>("R", 32);
        tablaAccion[32][6] = new Pair<>("R", 32);
        tablaAccion[32][8] = new Pair<>("R", 32);
        tablaAccion[32][20] = new Pair<>("R", 32);
        tablaAccion[32][21] = new Pair<>("R", 32);
        tablaAccion[32][22] = new Pair<>("S", 57);
        tablaAccion[32][23] = new Pair<>("S", 58);
        tablaAccion[33][3] = new Pair<>("R", 35);
        tablaAccion[33][6] = new Pair<>("R", 35);
        tablaAccion[33][8] = new Pair<>("R", 35);
        tablaAccion[33][20] = new Pair<>("R", 35);
        tablaAccion[33][21] = new Pair<>("R", 35);
        tablaAccion[33][22] = new Pair<>("R", 35);
        tablaAccion[33][23] = new Pair<>("R", 35);
        tablaAccion[33][24] = new Pair<>("S", 59);
        tablaAccion[33][25] = new Pair<>("S", 60);
        tablaAccion[34][3] = new Pair<>("R", 38);
        tablaAccion[34][6] = new Pair<>("R", 38);
        tablaAccion[34][8] = new Pair<>("R", 38);
        tablaAccion[34][20] = new Pair<>("R", 38);
        tablaAccion[34][21] = new Pair<>("R", 38);
        tablaAccion[34][22] = new Pair<>("R", 38);
        tablaAccion[34][23] = new Pair<>("R", 38);
        tablaAccion[34][24] = new Pair<>("R", 38);
        tablaAccion[34][25] = new Pair<>("R", 38);
        tablaAccion[35][2] = new Pair<>("S", 61);
        tablaAccion[35][3] = new Pair<>("R", 39);
        tablaAccion[35][6] = new Pair<>("R", 39);
        tablaAccion[35][8] = new Pair<>("R", 39);
        tablaAccion[35][20] = new Pair<>("R", 39);
        tablaAccion[35][21] = new Pair<>("R", 39);
        tablaAccion[35][22] = new Pair<>("R", 39);
        tablaAccion[35][23] = new Pair<>("R", 39);
        tablaAccion[35][24] = new Pair<>("R", 39);
        tablaAccion[35][25] = new Pair<>("R", 39);
        tablaAccion[36][1] = new Pair<>("S", 35);
        tablaAccion[36][2] = new Pair<>("S", 36);
        tablaAccion[36][26] = new Pair<>("S", 37);
        tablaAccion[36][27] = new Pair<>("S", 38);
        tablaAccion[37][3] = new Pair<>("R", 42);
        tablaAccion[37][6] = new Pair<>("R", 42);
        tablaAccion[37][8] = new Pair<>("R", 42);
        tablaAccion[37][20] = new Pair<>("R", 42);
        tablaAccion[37][21] = new Pair<>("R", 42);
        tablaAccion[37][22] = new Pair<>("R", 42);
        tablaAccion[37][23] = new Pair<>("R", 42);
        tablaAccion[37][24] = new Pair<>("R", 42);
        tablaAccion[37][25] = new Pair<>("R", 42);
        tablaAccion[38][3] = new Pair<>("R", 43);
        tablaAccion[38][6] = new Pair<>("R", 43);
        tablaAccion[38][8] = new Pair<>("R", 43);
        tablaAccion[38][20] = new Pair<>("R", 43);
        tablaAccion[38][21] = new Pair<>("R", 43);
        tablaAccion[38][22] = new Pair<>("R", 43);
        tablaAccion[38][23] = new Pair<>("R", 43);
        tablaAccion[38][24] = new Pair<>("R", 43);
        tablaAccion[38][25] = new Pair<>("R", 43);
        tablaAccion[39][1] = new Pair<>("S", 63);
        tablaAccion[40][1] = new Pair<>("R", 8);
        tablaAccion[41][3] = new Pair<>("S", 64);
        tablaAccion[41][20] = new Pair<>("S", 55);
        tablaAccion[42][8] = new Pair<>("S", 65);
        tablaAccion[43][5] = new Pair<>("S", 66);
        tablaAccion[44][0] = new Pair<>("R", 4);
        tablaAccion[44][1] = new Pair<>("R", 4);
        tablaAccion[44][9] = new Pair<>("R", 4);
        tablaAccion[44][10] = new Pair<>("R", 4);
        tablaAccion[44][11] = new Pair<>("R", 4);
        tablaAccion[44][13] = new Pair<>("R", 4);
        tablaAccion[44][14] = new Pair<>("R", 4);
        tablaAccion[44][15] = new Pair<>("R", 4);
        tablaAccion[44][28] = new Pair<>("R", 4);
        tablaAccion[45][1] = new Pair<>("S", 9);
        tablaAccion[45][3] = new Pair<>("R", 15);
        tablaAccion[45][5] = new Pair<>("R", 15);
        tablaAccion[45][9] = new Pair<>("S", 10);
        tablaAccion[45][10] = new Pair<>("S", 11);
        tablaAccion[45][11] = new Pair<>("S", 12);
        tablaAccion[45][13] = new Pair<>("S", 4);
        tablaAccion[45][14] = new Pair<>("S", 5);
        tablaAccion[45][15] = new Pair<>("S", 7);
        tablaAccion[46][3] = new Pair<>("S", 69);
        tablaAccion[47][1] = new Pair<>("S", 70);
        tablaAccion[48][8] = new Pair<>("S", 71);
        tablaAccion[48][20] = new Pair<>("S", 55);
        tablaAccion[49][3] = new Pair<>("S", 72);
        tablaAccion[50][3] = new Pair<>("R", 47);
        tablaAccion[50][6] = new Pair<>("S", 74);
        tablaAccion[50][8] = new Pair<>("R", 47);
        tablaAccion[50][20] = new Pair<>("S", 55);
        tablaAccion[51][8] = new Pair<>("S", 75);
        tablaAccion[52][3] = new Pair<>("S", 76);
        tablaAccion[52][20] = new Pair<>("S", 55);
        tablaAccion[53][3] = new Pair<>("S", 77);
        tablaAccion[54][0] = new Pair<>("R", 20);
        tablaAccion[54][1] = new Pair<>("R", 20);
        tablaAccion[54][3] = new Pair<>("R", 20);
        tablaAccion[54][5] = new Pair<>("R", 20);
        tablaAccion[54][9] = new Pair<>("R", 20);
        tablaAccion[54][10] = new Pair<>("R", 20);
        tablaAccion[54][11] = new Pair<>("R", 20);
        tablaAccion[54][13] = new Pair<>("R", 20);
        tablaAccion[54][14] = new Pair<>("R", 20);
        tablaAccion[54][15] = new Pair<>("R", 20);
        tablaAccion[54][28] = new Pair<>("R", 20);
        tablaAccion[55][1] = new Pair<>("S", 35);
        tablaAccion[55][2] = new Pair<>("S", 36);
        tablaAccion[55][26] = new Pair<>("S", 37);
        tablaAccion[55][27] = new Pair<>("S", 38);
        tablaAccion[56][1] = new Pair<>("S", 35);
        tablaAccion[56][2] = new Pair<>("S", 36);
        tablaAccion[56][26] = new Pair<>("S", 37);
        tablaAccion[56][27] = new Pair<>("S", 38);
        tablaAccion[57][1] = new Pair<>("S", 35);
        tablaAccion[57][2] = new Pair<>("S", 36);
        tablaAccion[57][26] = new Pair<>("S", 37);
        tablaAccion[57][27] = new Pair<>("S", 38);
        tablaAccion[58][1] = new Pair<>("S", 35);
        tablaAccion[58][2] = new Pair<>("S", 36);
        tablaAccion[58][26] = new Pair<>("S", 37);
        tablaAccion[58][27] = new Pair<>("S", 38);
        tablaAccion[59][1] = new Pair<>("S", 35);
        tablaAccion[59][2] = new Pair<>("S", 36);
        tablaAccion[59][26] = new Pair<>("S", 37);
        tablaAccion[59][27] = new Pair<>("S", 38);
        tablaAccion[60][1] = new Pair<>("S", 35);
        tablaAccion[60][2] = new Pair<>("S", 36);
        tablaAccion[60][26] = new Pair<>("S", 37);
        tablaAccion[60][27] = new Pair<>("S", 38);
        tablaAccion[61][1] = new Pair<>("S", 35);
        tablaAccion[61][2] = new Pair<>("S", 36);
        tablaAccion[61][3] = new Pair<>("R", 45);
        tablaAccion[61][8] = new Pair<>("R", 45);
        tablaAccion[61][26] = new Pair<>("S", 37);
        tablaAccion[61][27] = new Pair<>("S", 38);
        tablaAccion[62][3] = new Pair<>("S", 85);
        tablaAccion[62][20] = new Pair<>("S", 55);
        tablaAccion[63][2] = new Pair<>("R", 5);
        tablaAccion[64][1] = new Pair<>("S", 9);
        tablaAccion[64][9] = new Pair<>("S", 10);
        tablaAccion[64][10] = new Pair<>("S", 11);
        tablaAccion[64][11] = new Pair<>("S", 12);
        tablaAccion[65][0] = new Pair<>("R", 23);
        tablaAccion[65][1] = new Pair<>("R", 23);
        tablaAccion[65][3] = new Pair<>("R", 23);
        tablaAccion[65][5] = new Pair<>("R", 23);
        tablaAccion[65][9] = new Pair<>("R", 23);
        tablaAccion[65][10] = new Pair<>("R", 23);
        tablaAccion[65][11] = new Pair<>("R", 23);
        tablaAccion[65][13] = new Pair<>("R", 23);
        tablaAccion[65][14] = new Pair<>("R", 23);
        tablaAccion[65][15] = new Pair<>("R", 23);
        tablaAccion[65][28] = new Pair<>("R", 23);
        tablaAccion[66][16] = new Pair<>("S", 87);
        tablaAccion[67][5] = new Pair<>("S", 88);
        tablaAccion[68][1] = new Pair<>("S", 9);
        tablaAccion[68][3] = new Pair<>("R", 15);
        tablaAccion[68][5] = new Pair<>("R", 15);
        tablaAccion[68][9] = new Pair<>("S", 10);
        tablaAccion[68][10] = new Pair<>("S", 11);
        tablaAccion[68][11] = new Pair<>("S", 12);
        tablaAccion[68][13] = new Pair<>("S", 4);
        tablaAccion[68][14] = new Pair<>("S", 5);
        tablaAccion[68][15] = new Pair<>("S", 7);
        tablaAccion[69][4] = new Pair<>("R", 6);
        tablaAccion[70][3] = new Pair<>("R", 13);
        tablaAccion[70][6] = new Pair<>("S", 91);
        tablaAccion[71][0] = new Pair<>("R", 16);
        tablaAccion[71][1] = new Pair<>("R", 16);
        tablaAccion[71][3] = new Pair<>("R", 16);
        tablaAccion[71][5] = new Pair<>("R", 16);
        tablaAccion[71][9] = new Pair<>("R", 16);
        tablaAccion[71][10] = new Pair<>("R", 16);
        tablaAccion[71][11] = new Pair<>("R", 16);
        tablaAccion[71][13] = new Pair<>("R", 16);
        tablaAccion[71][14] = new Pair<>("R", 16);
        tablaAccion[71][15] = new Pair<>("R", 16);
        tablaAccion[71][28] = new Pair<>("R", 16);
        tablaAccion[72][8] = new Pair<>("S", 92);
        tablaAccion[73][3] = new Pair<>("R", 44);
        tablaAccion[73][8] = new Pair<>("R", 44);
        tablaAccion[74][1] = new Pair<>("S", 35);
        tablaAccion[74][2] = new Pair<>("S", 36);
        tablaAccion[74][26] = new Pair<>("S", 37);
        tablaAccion[74][27] = new Pair<>("S", 38);
        tablaAccion[75][0] = new Pair<>("R", 21);
        tablaAccion[75][1] = new Pair<>("R", 21);
        tablaAccion[75][3] = new Pair<>("R", 21);
        tablaAccion[75][5] = new Pair<>("R", 21);
        tablaAccion[75][9] = new Pair<>("R", 21);
        tablaAccion[75][10] = new Pair<>("R", 21);
        tablaAccion[75][11] = new Pair<>("R", 21);
        tablaAccion[75][13] = new Pair<>("R", 21);
        tablaAccion[75][14] = new Pair<>("R", 21);
        tablaAccion[75][15] = new Pair<>("R", 21);
        tablaAccion[75][28] = new Pair<>("R", 21);
        tablaAccion[76][8] = new Pair<>("S", 94);
        tablaAccion[77][8] = new Pair<>("S", 95);
        tablaAccion[78][3] = new Pair<>("R", 29);
        tablaAccion[78][6] = new Pair<>("R", 29);
        tablaAccion[78][8] = new Pair<>("R", 29);
        tablaAccion[78][20] = new Pair<>("R", 29);
        tablaAccion[78][21] = new Pair<>("S", 56);
        tablaAccion[79][3] = new Pair<>("R", 31);
        tablaAccion[79][6] = new Pair<>("R", 31);
        tablaAccion[79][8] = new Pair<>("R", 31);
        tablaAccion[79][20] = new Pair<>("R", 31);
        tablaAccion[79][21] = new Pair<>("R", 31);
        tablaAccion[79][22] = new Pair<>("S", 57);
        tablaAccion[79][23] = new Pair<>("S", 58);
        tablaAccion[80][3] = new Pair<>("R", 33);
        tablaAccion[80][6] = new Pair<>("R", 33);
        tablaAccion[80][8] = new Pair<>("R", 33);
        tablaAccion[80][20] = new Pair<>("R", 33);
        tablaAccion[80][21] = new Pair<>("R", 33);
        tablaAccion[80][22] = new Pair<>("R", 33);
        tablaAccion[80][23] = new Pair<>("R", 33);
        tablaAccion[80][24] = new Pair<>("S", 59);
        tablaAccion[80][25] = new Pair<>("S", 60);
        tablaAccion[81][3] = new Pair<>("R", 34);
        tablaAccion[81][6] = new Pair<>("R", 34);
        tablaAccion[81][8] = new Pair<>("R", 34);
        tablaAccion[81][20] = new Pair<>("R", 34);
        tablaAccion[81][21] = new Pair<>("R", 34);
        tablaAccion[81][22] = new Pair<>("R", 34);
        tablaAccion[81][23] = new Pair<>("R", 34);
        tablaAccion[81][24] = new Pair<>("S", 59);
        tablaAccion[81][25] = new Pair<>("S", 60);
        tablaAccion[82][3] = new Pair<>("R", 36);
        tablaAccion[82][6] = new Pair<>("R", 36);
        tablaAccion[82][8] = new Pair<>("R", 36);
        tablaAccion[82][20] = new Pair<>("R", 36);
        tablaAccion[82][21] = new Pair<>("R", 36);
        tablaAccion[82][22] = new Pair<>("R", 36);
        tablaAccion[82][23] = new Pair<>("R", 36);
        tablaAccion[82][24] = new Pair<>("R", 36);
        tablaAccion[82][25] = new Pair<>("R", 36);
        tablaAccion[83][3] = new Pair<>("R", 37);
        tablaAccion[83][6] = new Pair<>("R", 37);
        tablaAccion[83][8] = new Pair<>("R", 37);
        tablaAccion[83][20] = new Pair<>("R", 37);
        tablaAccion[83][21] = new Pair<>("R", 37);
        tablaAccion[83][22] = new Pair<>("R", 37);
        tablaAccion[83][23] = new Pair<>("R", 37);
        tablaAccion[83][24] = new Pair<>("R", 37);
        tablaAccion[83][25] = new Pair<>("R", 37);
        tablaAccion[84][3] = new Pair<>("S", 96);
        tablaAccion[85][3] = new Pair<>("R", 40);
        tablaAccion[85][6] = new Pair<>("R", 40);
        tablaAccion[85][8] = new Pair<>("R", 40);
        tablaAccion[85][20] = new Pair<>("R", 40);
        tablaAccion[85][21] = new Pair<>("R", 40);
        tablaAccion[85][22] = new Pair<>("R", 40);
        tablaAccion[85][23] = new Pair<>("R", 40);
        tablaAccion[85][24] = new Pair<>("R", 40);
        tablaAccion[85][25] = new Pair<>("R", 40);
        tablaAccion[86][0] = new Pair<>("R", 22);
        tablaAccion[86][1] = new Pair<>("R", 22);
        tablaAccion[86][3] = new Pair<>("R", 22);
        tablaAccion[86][5] = new Pair<>("R", 22);
        tablaAccion[86][9] = new Pair<>("R", 22);
        tablaAccion[86][10] = new Pair<>("R", 22);
        tablaAccion[86][11] = new Pair<>("R", 22);
        tablaAccion[86][13] = new Pair<>("R", 22);
        tablaAccion[86][14] = new Pair<>("R", 22);
        tablaAccion[86][15] = new Pair<>("R", 22);
        tablaAccion[86][28] = new Pair<>("R", 22);
        tablaAccion[87][2] = new Pair<>("S", 97);
        tablaAccion[88][0] = new Pair<>("R", 7);
        tablaAccion[88][1] = new Pair<>("R", 7);
        tablaAccion[88][9] = new Pair<>("R", 7);
        tablaAccion[88][10] = new Pair<>("R", 7);
        tablaAccion[88][11] = new Pair<>("R", 7);
        tablaAccion[88][13] = new Pair<>("R", 7);
        tablaAccion[88][14] = new Pair<>("R", 7);
        tablaAccion[88][15] = new Pair<>("R", 7);
        tablaAccion[88][28] = new Pair<>("R", 7);
        tablaAccion[89][3] = new Pair<>("R", 14);
        tablaAccion[89][5] = new Pair<>("R", 14);
        tablaAccion[90][3] = new Pair<>("R", 10);
        tablaAccion[91][17] = new Pair<>("S", 18);
        tablaAccion[91][18] = new Pair<>("S", 19);
        tablaAccion[91][19] = new Pair<>("S", 20);
        tablaAccion[92][0] = new Pair<>("R", 17);
        tablaAccion[92][1] = new Pair<>("R", 17);
        tablaAccion[92][3] = new Pair<>("R", 17);
        tablaAccion[92][5] = new Pair<>("R", 17);
        tablaAccion[92][9] = new Pair<>("R", 17);
        tablaAccion[92][10] = new Pair<>("R", 17);
        tablaAccion[92][11] = new Pair<>("R", 17);
        tablaAccion[92][13] = new Pair<>("R", 17);
        tablaAccion[92][14] = new Pair<>("R", 17);
        tablaAccion[92][15] = new Pair<>("R", 17);
        tablaAccion[92][28] = new Pair<>("R", 17);
        tablaAccion[93][3] = new Pair<>("R", 47);
        tablaAccion[93][6] = new Pair<>("S", 74);
        tablaAccion[93][8] = new Pair<>("R", 47);
        tablaAccion[93][20] = new Pair<>("S", 55);
        tablaAccion[94][0] = new Pair<>("R", 18);
        tablaAccion[94][1] = new Pair<>("R", 18);
        tablaAccion[94][3] = new Pair<>("R", 18);
        tablaAccion[94][5] = new Pair<>("R", 18);
        tablaAccion[94][9] = new Pair<>("R", 18);
        tablaAccion[94][10] = new Pair<>("R", 18);
        tablaAccion[94][11] = new Pair<>("R", 18);
        tablaAccion[94][13] = new Pair<>("R", 18);
        tablaAccion[94][14] = new Pair<>("R", 18);
        tablaAccion[94][15] = new Pair<>("R", 18);
        tablaAccion[94][28] = new Pair<>("R", 18);
        tablaAccion[95][0] = new Pair<>("R", 19);
        tablaAccion[95][1] = new Pair<>("R", 19);
        tablaAccion[95][3] = new Pair<>("R", 19);
        tablaAccion[95][5] = new Pair<>("R", 19);
        tablaAccion[95][9] = new Pair<>("R", 19);
        tablaAccion[95][10] = new Pair<>("R", 19);
        tablaAccion[95][11] = new Pair<>("R", 19);
        tablaAccion[95][13] = new Pair<>("R", 19);
        tablaAccion[95][14] = new Pair<>("R", 19);
        tablaAccion[95][15] = new Pair<>("R", 19);
        tablaAccion[95][28] = new Pair<>("R", 19);
        tablaAccion[96][3] = new Pair<>("R", 41);
        tablaAccion[96][6] = new Pair<>("R", 41);
        tablaAccion[96][8] = new Pair<>("R", 41);
        tablaAccion[96][20] = new Pair<>("R", 41);
        tablaAccion[96][21] = new Pair<>("R", 41);
        tablaAccion[96][22] = new Pair<>("R", 41);
        tablaAccion[96][23] = new Pair<>("R", 41);
        tablaAccion[96][24] = new Pair<>("R", 41);
        tablaAccion[96][25] = new Pair<>("R", 41);
        tablaAccion[97][1] = new Pair<>("S", 9);
        tablaAccion[97][3] = new Pair<>("R", 15);
        tablaAccion[97][5] = new Pair<>("R", 15);
        tablaAccion[97][9] = new Pair<>("S", 10);
        tablaAccion[97][10] = new Pair<>("S", 11);
        tablaAccion[97][11] = new Pair<>("S", 12);
        tablaAccion[97][13] = new Pair<>("S", 4);
        tablaAccion[97][14] = new Pair<>("S", 5);
        tablaAccion[97][15] = new Pair<>("S", 7);
        tablaAccion[98][1] = new Pair<>("S", 101);
        tablaAccion[99][3] = new Pair<>("R", 46);
        tablaAccion[99][8] = new Pair<>("R", 46);
        tablaAccion[100][3] = new Pair<>("S", 102);
        tablaAccion[101][3] = new Pair<>("R", 13);
        tablaAccion[101][6] = new Pair<>("S", 91);
        tablaAccion[102][8] = new Pair<>("S", 104);
        tablaAccion[103][3] = new Pair<>("R", 12);
        tablaAccion[104][0] = new Pair<>("R", 25);
        tablaAccion[104][1] = new Pair<>("R", 25);
        tablaAccion[104][3] = new Pair<>("R", 25);
        tablaAccion[104][5] = new Pair<>("R", 25);
        tablaAccion[104][9] = new Pair<>("R", 25);
        tablaAccion[104][10] = new Pair<>("R", 25);
        tablaAccion[104][11] = new Pair<>("R", 25);
        tablaAccion[104][13] = new Pair<>("R", 25);
        tablaAccion[104][14] = new Pair<>("R", 25);
        tablaAccion[104][15] = new Pair<>("R", 25);
        tablaAccion[104][28] = new Pair<>("R", 25);
        return tablaAccion;
    }

    public static int[][] tablaGoTo() {
        int[][] tablaGoTo = new int[105][21];
        tablaGoTo[0][1] = 1;
        tablaGoTo[0][2] = 3;
        tablaGoTo[0][3] = 8;
        tablaGoTo[0][10] = 6;
        tablaGoTo[0][11] = 2;
        tablaGoTo[2][1] = 14;
        tablaGoTo[2][2] = 3;
        tablaGoTo[2][3] = 8;
        tablaGoTo[2][10] = 6;
        tablaGoTo[2][11] = 2;
        tablaGoTo[3][1] = 15;
        tablaGoTo[3][2] = 3;
        tablaGoTo[3][3] = 8;
        tablaGoTo[3][10] = 6;
        tablaGoTo[3][11] = 2;
        tablaGoTo[5][12] = 17;
        tablaGoTo[8][4] = 22;
        tablaGoTo[12][13] = 30;
        tablaGoTo[12][14] = 31;
        tablaGoTo[12][15] = 32;
        tablaGoTo[12][16] = 33;
        tablaGoTo[12][17] = 34;
        tablaGoTo[12][20] = 29;
        tablaGoTo[13][6] = 39;
        tablaGoTo[13][12] = 40;
        tablaGoTo[16][13] = 41;
        tablaGoTo[16][14] = 31;
        tablaGoTo[16][15] = 32;
        tablaGoTo[16][16] = 33;
        tablaGoTo[16][17] = 34;
        tablaGoTo[21][10] = 6;
        tablaGoTo[21][11] = 43;
        tablaGoTo[22][5] = 44;
        tablaGoTo[23][7] = 46;
        tablaGoTo[23][12] = 47;
        tablaGoTo[24][13] = 48;
        tablaGoTo[24][14] = 31;
        tablaGoTo[24][15] = 32;
        tablaGoTo[24][16] = 33;
        tablaGoTo[24][17] = 34;
        tablaGoTo[25][13] = 50;
        tablaGoTo[25][14] = 31;
        tablaGoTo[25][15] = 32;
        tablaGoTo[25][16] = 33;
        tablaGoTo[25][17] = 34;
        tablaGoTo[25][18] = 49;
        tablaGoTo[26][13] = 50;
        tablaGoTo[26][14] = 31;
        tablaGoTo[26][15] = 32;
        tablaGoTo[26][16] = 33;
        tablaGoTo[26][17] = 34;
        tablaGoTo[26][18] = 51;
        tablaGoTo[27][13] = 52;
        tablaGoTo[27][14] = 31;
        tablaGoTo[27][15] = 32;
        tablaGoTo[27][16] = 33;
        tablaGoTo[27][17] = 34;
        tablaGoTo[36][13] = 62;
        tablaGoTo[36][14] = 31;
        tablaGoTo[36][15] = 32;
        tablaGoTo[36][16] = 33;
        tablaGoTo[36][17] = 34;
        tablaGoTo[45][9] = 67;
        tablaGoTo[45][10] = 6;
        tablaGoTo[45][11] = 68;
        tablaGoTo[50][19] = 73;
        tablaGoTo[55][14] = 78;
        tablaGoTo[55][15] = 32;
        tablaGoTo[55][16] = 33;
        tablaGoTo[55][17] = 34;
        tablaGoTo[56][15] = 79;
        tablaGoTo[56][16] = 33;
        tablaGoTo[56][17] = 34;
        tablaGoTo[57][16] = 80;
        tablaGoTo[57][17] = 34;
        tablaGoTo[58][16] = 81;
        tablaGoTo[58][17] = 34;
        tablaGoTo[59][17] = 82;
        tablaGoTo[60][17] = 83;
        tablaGoTo[61][13] = 50;
        tablaGoTo[61][14] = 31;
        tablaGoTo[61][15] = 32;
        tablaGoTo[61][16] = 33;
        tablaGoTo[61][17] = 34;
        tablaGoTo[61][18] = 84;
        tablaGoTo[64][10] = 86;
        tablaGoTo[68][9] = 89;
        tablaGoTo[68][10] = 6;
        tablaGoTo[68][11] = 68;
        tablaGoTo[70][8] = 90;
        tablaGoTo[74][13] = 93;
        tablaGoTo[74][14] = 31;
        tablaGoTo[74][15] = 32;
        tablaGoTo[74][16] = 33;
        tablaGoTo[74][17] = 34;
        tablaGoTo[91][12] = 98;
        tablaGoTo[93][19] = 99;
        tablaGoTo[97][9] = 100;
        tablaGoTo[97][10] = 6;
        tablaGoTo[97][11] = 68;
        tablaGoTo[101][8] = 103;
        return tablaGoTo;
    }

    public static HashMap<String, Integer> accionHashMap() {
        HashMap<String, Integer> aplicacionTerminal = new HashMap<>();
        aplicacionTerminal.put("function", 0);
        aplicacionTerminal.put("identificador", 1);
        aplicacionTerminal.put("abrirParentesis", 2);
        aplicacionTerminal.put("cerrarParentesis", 3);
        aplicacionTerminal.put("abrirCorchete", 4);
        aplicacionTerminal.put("cerrarCorchete", 5);
        aplicacionTerminal.put("coma", 6);
        aplicacionTerminal.put("asignacion", 7);
        aplicacionTerminal.put("puntoYcoma", 8);
        aplicacionTerminal.put("alert", 9);
        aplicacionTerminal.put("input", 10);
        aplicacionTerminal.put("return", 11);
        aplicacionTerminal.put("restaAsignacion", 12);
        aplicacionTerminal.put("if", 13);
        aplicacionTerminal.put("let", 14);
        aplicacionTerminal.put("do", 15);
        aplicacionTerminal.put("while", 16);
        aplicacionTerminal.put("number", 17);
        aplicacionTerminal.put("boolean", 18);
        aplicacionTerminal.put("string", 19);
        aplicacionTerminal.put("opLogico2", 20);
        aplicacionTerminal.put("opLogico1", 21);
        aplicacionTerminal.put("opRelacional1", 22);
        aplicacionTerminal.put("opRelacional2", 23);
        aplicacionTerminal.put("opAritmetico1", 24);
        aplicacionTerminal.put("opAritmetico2", 25);
        aplicacionTerminal.put("cteEntera", 26);
        aplicacionTerminal.put("cadena", 27);
        aplicacionTerminal.put("$", 28);
        return aplicacionTerminal;
    }

    public static HashMap<String, Integer> GoToHashMap() {
        HashMap<String, Integer> aplicacionNoTerminal = new HashMap<>();
        aplicacionNoTerminal.put("Z", 0);
        aplicacionNoTerminal.put("P", 1);
        aplicacionNoTerminal.put("F", 2);
        aplicacionNoTerminal.put("I", 3);
        aplicacionNoTerminal.put("J", 4);
        aplicacionNoTerminal.put("G", 5);
        aplicacionNoTerminal.put("H", 6);
        aplicacionNoTerminal.put("A", 7);
        aplicacionNoTerminal.put("K", 8);
        aplicacionNoTerminal.put("C", 9);
        aplicacionNoTerminal.put("S", 10);
        aplicacionNoTerminal.put("B", 11);
        aplicacionNoTerminal.put("T", 12);
        aplicacionNoTerminal.put("E", 13);
        aplicacionNoTerminal.put("R", 14);
        aplicacionNoTerminal.put("U", 15);
        aplicacionNoTerminal.put("V", 16);
        aplicacionNoTerminal.put("W", 17);
        aplicacionNoTerminal.put("L", 18);
        aplicacionNoTerminal.put("Q", 19);
        aplicacionNoTerminal.put("X", 20);
        return aplicacionNoTerminal;
    }

    public static Pair<String, Integer>[] gramaticaArray() {
        Pair<String, Integer>[] gramaticaDepurada = new Pair[50];
        gramaticaDepurada[0] = new Pair<String, Integer>("Z", 1);
        gramaticaDepurada[1] = new Pair<String, Integer>("P", 2);
        gramaticaDepurada[2] = new Pair<String, Integer>("P", 2);
        gramaticaDepurada[3] = new Pair<String, Integer>("P", 0);
        gramaticaDepurada[4] = new Pair<String, Integer>("F", 3);
        gramaticaDepurada[5] = new Pair<String, Integer>("I", 3);
        gramaticaDepurada[6] = new Pair<String, Integer>("J", 3);
        gramaticaDepurada[7] = new Pair<String, Integer>("G", 3);
        gramaticaDepurada[8] = new Pair<String, Integer>("H", 1);
        gramaticaDepurada[9] = new Pair<String, Integer>("H", 0);
        gramaticaDepurada[10] = new Pair<String, Integer>("A", 3);
        gramaticaDepurada[11] = new Pair<String, Integer>("A", 0);
        gramaticaDepurada[12] = new Pair<String, Integer>("K", 4);
        gramaticaDepurada[13] = new Pair<String, Integer>("K", 0);
        gramaticaDepurada[14] = new Pair<String, Integer>("C", 2);
        gramaticaDepurada[15] = new Pair<String, Integer>("C", 0);
        gramaticaDepurada[16] = new Pair<String, Integer>("S", 4);
        gramaticaDepurada[17] = new Pair<String, Integer>("S", 5);
        gramaticaDepurada[18] = new Pair<String, Integer>("S", 5);
        gramaticaDepurada[19] = new Pair<String, Integer>("S", 5);
        gramaticaDepurada[20] = new Pair<String, Integer>("S", 3);
        gramaticaDepurada[21] = new Pair<String, Integer>("S", 4);
        gramaticaDepurada[22] = new Pair<String, Integer>("B", 5);
        gramaticaDepurada[23] = new Pair<String, Integer>("B", 4);
        gramaticaDepurada[24] = new Pair<String, Integer>("B", 1);
        gramaticaDepurada[25] = new Pair<String, Integer>("B", 9);
        gramaticaDepurada[26] = new Pair<String, Integer>("T", 1);
        gramaticaDepurada[27] = new Pair<String, Integer>("T", 1);
        gramaticaDepurada[28] = new Pair<String, Integer>("T", 1);
        gramaticaDepurada[29] = new Pair<String, Integer>("E", 3);
        gramaticaDepurada[30] = new Pair<String, Integer>("E", 1);
        gramaticaDepurada[31] = new Pair<String, Integer>("R", 3);
        gramaticaDepurada[32] = new Pair<String, Integer>("R", 1);
        gramaticaDepurada[33] = new Pair<String, Integer>("U", 3);
        gramaticaDepurada[34] = new Pair<String, Integer>("U", 3);
        gramaticaDepurada[35] = new Pair<String, Integer>("U", 1);
        gramaticaDepurada[36] = new Pair<String, Integer>("V", 3);
        gramaticaDepurada[37] = new Pair<String, Integer>("V", 3);
        gramaticaDepurada[38] = new Pair<String, Integer>("V", 1);
        gramaticaDepurada[39] = new Pair<String, Integer>("W", 1);
        gramaticaDepurada[40] = new Pair<String, Integer>("W", 3);
        gramaticaDepurada[41] = new Pair<String, Integer>("W", 4);
        gramaticaDepurada[42] = new Pair<String, Integer>("W", 1);
        gramaticaDepurada[43] = new Pair<String, Integer>("W", 1);
        gramaticaDepurada[44] = new Pair<String, Integer>("L", 2);
        gramaticaDepurada[45] = new Pair<String, Integer>("L", 0);
        gramaticaDepurada[46] = new Pair<String, Integer>("Q", 3);
        gramaticaDepurada[47] = new Pair<String, Integer>("Q", 0);
        gramaticaDepurada[48] = new Pair<String, Integer>("X", 1);
        gramaticaDepurada[49] = new Pair<String, Integer>("X", 0);
        return gramaticaDepurada;
    }
}
